### ISSUE TITLE
Issue when using the "Lancer l'analyse des IFs" feature

### ISSUE THREAD

**Issue by BaptisteRefalo** [TickyWill/BiblioMeter#1]
Using this feature does not give any result and the app seems to continuously working without doing anything.

Issue origin in code:
BM_PubAnalysis.py -> if_analysis() -> _plot_if_analysis() -> _create_save_barchart() -> _save_dept_barchart()

`dept_png_file_path  = Path(if_analysis_folder_path) / Path(file_name + ".png")`
`barchart.write_image(dept_png_file_path)`
-> this issue seems to come from the line above: saving the barchart in a png file. The rest of the code is never executed
-> commenting those 2 lines removes the issue

**Comment by BaptisteRefalo** [comment]
Solution to this issue found:
https://stackoverflow.com/questions/69016568/unable-to-export-plotly-images-to-png-with-kaleido

-> This is a "kaleido 0.2" problem

**Comment by BaptisteRefalo** [comment]
I tested using the kaleido v0.1.* and it worked

**Comment by BaptisteRefalo** [comment]
https://github.com/plotly/Kaleido/issues/170

**Comment by TickyWill** [comment]
Requirements.txt updated by changing kaleido version from v0.2.# to v0.1.*
Thanks for reporting the issue and its solution !
