### ISSUE TITLE
fail to when launchin "Lancer l'analyse des mots clefs"

### ISSUE THREAD

**Issue by Bertin-fap** [TickyWill/BiblioMeter#2]
When launching "Lancer l'analyse des mots clefs" the following error occurs in the wordcloud package:

File "C:\Users\franc\PyVenv\BiblioMeter\venv\lib\site-packages\wordcloud\wordcloud.py", line 106, in __init__
    self.colormap = plt.cm.get_cmap(colormap)

This issue is due to the release of matplotlib 3.9.0 on 16-05-2024. This version is no more compatible with wordcloud. For more detail
see : fix AttributeError when using matplotlib>=3.9.0 by gly11 · Pull Request #57 · luciddreamer-cvlab/LucidDreamer (github.com)](https://github.com/luciddreamer-cvlab/LucidDreamer/pull/57/commits/bb777f46f9ba6c7bb11abbe96bd18a93ecabbb9b)

To fix this bug I raise the following issue:
https://github.com/amueller/word_cloud/issues/765

Before the bug is fixed we have to use the version 3.8.0 of matplotlib  so the requirements.txt should read:
auto_py_to_exe==2.42.0
kaleido==0.2.1
plotly==5.17.0
screeninfo==0.8.1
matplotlib==3.8.4
wordcloud==1.9.2

**Comment by TickyWill** [comment]
requirements.txt updated by adding matplotlib==3.8.4 before wordcloud==1.9.2 to force matplotlib version to wordcloud.
This is a temporary solution untill the incompatibility between wordcloud v1.9.2 and matplotlib v3.9.0 is solved by owners.
Please take care of kaleido version (see [https://github.com/TickyWill/BiblioMeter/issues/1](url)).
Thanks for reporting this issue and its solution.

**Comment by BaptisteRefalo** [comment]
The wordcloud version 1.9.3 works well with the version 3.9.0 of matplotlib -> I no longer have this issue with that fix

**Comment by TickyWill** [comment]
Thanks for the update. These libraries are no more used in the v5.1 release of BiblioMeter. But we will keep it in mind for the complementary application under development.
